### ISSUE TITLE
Undefined Factory

### ISSUE THREAD

**Issue by saderra** [elastic/app-search-magento#63]
Installation on a fresh magento 2.3.3 install, LAMP, multi-store configuration results in the following when attempting to search: 

1 exception(s):
Exception #0 (DomainException): Undefined factory elastic_appsearch

**Comment by afoucret** [comment]
Hi @saderra,

This bug is caused by the introduction of breaking change in the way layered navigation is managed in Magento 2.3.2. This issue on the Magento repo is kind of related: magento/magento2#23615

I have just merged the PR #64 that is intended to fix it and ensure compatibility with this change (without losing support for older versions). You can test it from the master branch as soon as now.

I will also release a new beta very soon that will contains the fix.

Thank you for reporting this.
