### ISSUE TITLE
Another Issue

### ISSUE THREAD

**Issue by saderra** [elastic/app-search-magento#66]
Another issue has arisen when your module is installed on 2.3.2, without the other aforementioned extension: 

Compare this site on our live production site: 
https://classicaccessories.com/patio-furniture-cushions/lounge-chair-cushions

This site is a direct backup of that site, with the finder module disabled and your extension enabled: https://c1.saderra.com/patio-furniture-cushions/lounge-chair-cushions

The error is: [2019-10-16 01:57:55] main.INFO: Reference to undeclared plugin with name 'stockedProductsFilterPlugin'. This seems to be discussed here: 

https://github.com/magento/inventory/blob/d956bd063d2d35f75c58c0e48cdfa31db28b4efd/app/code/Magento/InventoryElasticsearch/etc/di.xml#L10

**Comment by afoucret** [comment]
This issue is a well-known issue affecting Magento 2.3.2 (https://github.com/magento/inventory/issues/2590). 

This has been fixed by the MSI team (Multi Source Inventory) in Magento 2.3.3.

Are you using developer mode for this specific environment?
In this case, I suspect that it will happen even if our module is disabled.

I also suspect that it may occur in your production system if using the DI compile:
```
bin/magento setup:di:compile
```

Can you confirm both of these assertions?

**Comment by afoucret** [comment]
Hi @saderra,

Have you been able to investigate on this one and to confirm it is not related to the module?

If my intuition is right, you should upgrade to Magento 2.3.3 (especially if you are unable to compile the DI on your production).

**Comment by saderra** [comment]
I have not. We can close this ticket for now. I'll reach back out when we get more into our 2.3.3 rebuild.
