### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by saderra** [elastic/app-search-magento#67]
We are seeing the following error generated by this plugin: 
"query_params":[]},"error":"Rate limit exceeded"} []

How do we manage this?

**Comment by saderra** [comment]
Following up on this. Status please. Thank you :)

**Comment by JasonStoltz** [comment]
Hi @saderra, @afoucret is is out this week and likely won't have a chance to look into this.

I'm not certain how indexing happens in the Magento Plugin, but the App Search API is rate limited, which is described here: https://swiftype.com/documentation/app-search/api/overview#rate-limiting.

The best advice I'd have to offer is to try to limit the number of documents you are trying to index per hour.

How far off are you with indexing?

**Comment by afoucret** [comment]
I had a chance to investigate the case and it appears that 3 things can explain a such a high request rate.

# 1. Deleted documents purge mechanisms:
During indexing deleted docs are only flagged as deleted but kept into the engine.
The main reason to proceed like this is that we want to be able to wait for the updates to be searchable to clean Magento caches layers. To detect this condition we run searches (with empty text but filter on a special field containing the batch id) until all docs are indexed into the search engine.

The module also comes with a cron executed every minute that will search for doc marked for deletion and effectively delete them. By running every minute this task will generate at least 1440 search requests (`60 * 24`) per day.

Running cleanup as such a high frequency is not required from a functional perspective and I will propose a patch today to run it only every hour.

# 2. Categories browsing:
Search requests are not only issued when using the search bar but also when browsing the catalog using categories navigation. These requests do not specify any search term but filters only. It is in charge of building the products list and facets (layered navigation in the Magento jargon).

These requests are easy to spot using analytics because it uses the `catalog_view_container` analytics tags.

In a standard Magento setup, these pages can benefit of the FPC caching (full page cache) to serve the same page to several customers. It is originally designed to improve Magento performance but that will reduce the number of queries in our context.

On some websites the FPC mechanism is disabled:

* intentionally to prevent caching for some specific dev that does not handle caches layers correctly
* unintentionally by a third party module (that disable cache for a block)
I have checked on my dev instance (luma theme + sample data) and only one request is issued for each page and the FPC mechanism can be enabled in the same way than for a standard Magento. I would recommend that you investigate this mechanism. If disabled, it should be enabled to save search requests.

# 3. Third-party modules
I know you are using some third-party modules by Amasty (Part Finder at least). These modules are known to use the search engine to build some specific use cases. It may be worthy to investigate and see what is the number of queries issued by these modules. They are also tagged as `catalog_view_container` but have a page size of `0` (only facets are used here).

**Comment by afoucret** [comment]
The PR #69 fix the cron scheduling and should save around 1400 search requests a day.
It will be part of the next beta release.

I would encourage you to Investigate both your FPC configuration and how the Amasty module is using the Magento search engine if you still see high request rate.

**Comment by afoucret** [comment]
The release 1.0.0-beta4 has been published and contains the PR #69.

PS: You have to clean your caches after the module is upgraded in order to see the full patch effect.
